// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __student__data_hh__
#define __student__data_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_student__data
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_student__data
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_student__data
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



#ifndef __StudentInfo__
#define __StudentInfo__
class StudentInfo;
class _objref_StudentInfo;
class _impl_StudentInfo;

typedef _objref_StudentInfo* StudentInfo_ptr;
typedef StudentInfo_ptr StudentInfoRef;

class StudentInfo_Helper {
public:
  typedef StudentInfo_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_StudentInfo, StudentInfo_Helper> StudentInfo_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_StudentInfo,StudentInfo_Helper > StudentInfo_out;

#endif

// interface StudentInfo
class StudentInfo {
public:
  // Declarations for this interface type.
  typedef StudentInfo_ptr _ptr_type;
  typedef StudentInfo_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_StudentInfo :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  ::CORBA::Long SetStudentData();
  void GetStudentData();

  // Constructors
  inline _objref_StudentInfo()  { _PR_setobj(0); }  // nil
  _objref_StudentInfo(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_StudentInfo();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_StudentInfo(const _objref_StudentInfo&);
  _objref_StudentInfo& operator = (const _objref_StudentInfo&);
  // not implemented

  friend class StudentInfo;
};

class _pof_StudentInfo : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_StudentInfo() : _OMNI_NS(proxyObjectFactory)(StudentInfo::_PD_repoId) {}
  virtual ~_pof_StudentInfo();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_StudentInfo :
  public virtual omniServant
{
public:
  virtual ~_impl_StudentInfo();

  virtual ::CORBA::Long SetStudentData() = 0;
  virtual void GetStudentData() = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_StudentInfo :
  public virtual _impl_StudentInfo,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_StudentInfo();

  inline ::StudentInfo_ptr _this() {
    return (::StudentInfo_ptr) _do_this(::StudentInfo::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
StudentInfo::_marshalObjRef(::StudentInfo_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_student__data
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_student__data
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_student__data
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_student__data
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_student__data
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_student__data
#endif

#endif  // __student__data_hh__

