module Finance {
	typedef sequence<string> StringSeq;
	struct AccountDetails {
		string     name;
		StringSeq  address;
		long       account_number;
		double     current_balance;
	};
	exception insufficientFunds { };
	interface Account {
		void deposit(in double amount);
		void withdraw(in double amount) raises(insufficientFunds);
		readonly attribute AccountDetails details;
	};
};
