// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "account.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



SavingsAccount::Account_ptr SavingsAccount::Account_Helper::_nil() {
  return ::SavingsAccount::Account::_nil();
}

::CORBA::Boolean SavingsAccount::Account_Helper::is_nil(::SavingsAccount::Account_ptr p) {
  return ::CORBA::is_nil(p);

}

void SavingsAccount::Account_Helper::release(::SavingsAccount::Account_ptr p) {
  ::CORBA::release(p);
}

void SavingsAccount::Account_Helper::marshalObjRef(::SavingsAccount::Account_ptr obj, cdrStream& s) {
  ::SavingsAccount::Account::_marshalObjRef(obj, s);
}

SavingsAccount::Account_ptr SavingsAccount::Account_Helper::unmarshalObjRef(cdrStream& s) {
  return ::SavingsAccount::Account::_unmarshalObjRef(s);
}

void SavingsAccount::Account_Helper::duplicate(::SavingsAccount::Account_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

SavingsAccount::Account_ptr
SavingsAccount::Account::_duplicate(::SavingsAccount::Account_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

SavingsAccount::Account_ptr
SavingsAccount::Account::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


SavingsAccount::Account_ptr
SavingsAccount::Account::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

SavingsAccount::Account_ptr
SavingsAccount::Account::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Account _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Account* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Account;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* SavingsAccount::Account::_PD_repoId = "IDL:SavingsAccount/Account:1.0";


SavingsAccount::_objref_Account::~_objref_Account() {
  
}


SavingsAccount::_objref_Account::_objref_Account(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::SavingsAccount::Account::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
SavingsAccount::_objref_Account::_ptrToObjRef(const char* id)
{
  if (id == ::SavingsAccount::Account::_PD_repoId)
    return (::SavingsAccount::Account_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::SavingsAccount::Account::_PD_repoId))
    return (::SavingsAccount::Account_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for SavingsAccount::Account::getBalance

// Proxy call descriptor class. Mangled signature:
//  _cfloat
class _0RL_cd_4cbcfecae188e63d_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_4cbcfecae188e63d_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Float result;
};

void _0RL_cd_4cbcfecae188e63d_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_4cbcfecae188e63d_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Float&)result <<= _n;

}

const char* const _0RL_cd_4cbcfecae188e63d_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_4cbcfecae188e63d_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_4cbcfecae188e63d_00000000* tcd = (_0RL_cd_4cbcfecae188e63d_00000000*)cd;
  SavingsAccount::_impl_Account* impl = (SavingsAccount::_impl_Account*) svnt->_ptrToInterface(SavingsAccount::Account::_PD_repoId);
  tcd->result = impl->getBalance();


}

::CORBA::Float SavingsAccount::_objref_Account::getBalance()
{
  _0RL_cd_4cbcfecae188e63d_00000000 _call_desc(_0RL_lcfn_4cbcfecae188e63d_10000000, "getBalance", 11);


  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for SavingsAccount::Account::withdraw

// Proxy call descriptor class. Mangled signature:
//  _cfloat_i_cfloat
class _0RL_cd_4cbcfecae188e63d_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_4cbcfecae188e63d_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Float arg_0;
  ::CORBA::Float result;
};

void _0RL_cd_4cbcfecae188e63d_20000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_4cbcfecae188e63d_20000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Float&)arg_0 <<= _n;

}

void _0RL_cd_4cbcfecae188e63d_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_4cbcfecae188e63d_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Float&)result <<= _n;

}

const char* const _0RL_cd_4cbcfecae188e63d_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_4cbcfecae188e63d_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_4cbcfecae188e63d_20000000* tcd = (_0RL_cd_4cbcfecae188e63d_20000000*)cd;
  SavingsAccount::_impl_Account* impl = (SavingsAccount::_impl_Account*) svnt->_ptrToInterface(SavingsAccount::Account::_PD_repoId);
  tcd->result = impl->withdraw(tcd->arg_0);


}

::CORBA::Float SavingsAccount::_objref_Account::withdraw(::CORBA::Float withdrawalAmount)
{
  _0RL_cd_4cbcfecae188e63d_20000000 _call_desc(_0RL_lcfn_4cbcfecae188e63d_30000000, "withdraw", 9);
  _call_desc.arg_0 = withdrawalAmount;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for SavingsAccount::Account::deposit

// Local call call-back function.
static void
_0RL_lcfn_4cbcfecae188e63d_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_4cbcfecae188e63d_20000000* tcd = (_0RL_cd_4cbcfecae188e63d_20000000*)cd;
  SavingsAccount::_impl_Account* impl = (SavingsAccount::_impl_Account*) svnt->_ptrToInterface(SavingsAccount::Account::_PD_repoId);
  tcd->result = impl->deposit(tcd->arg_0);


}

::CORBA::Float SavingsAccount::_objref_Account::deposit(::CORBA::Float depositAmount)
{
  _0RL_cd_4cbcfecae188e63d_20000000 _call_desc(_0RL_lcfn_4cbcfecae188e63d_40000000, "deposit", 8);
  _call_desc.arg_0 = depositAmount;

  _invoke(_call_desc);
  return _call_desc.result;


}

SavingsAccount::_pof_Account::~_pof_Account() {}


omniObjRef*
SavingsAccount::_pof_Account::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::SavingsAccount::_objref_Account(ior, id);
}


::CORBA::Boolean
SavingsAccount::_pof_Account::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::SavingsAccount::Account::_PD_repoId))
    return 1;
  
  return 0;
}

const SavingsAccount::_pof_Account _the_pof_SavingsAccount_mAccount;

SavingsAccount::_impl_Account::~_impl_Account() {}


::CORBA::Boolean
SavingsAccount::_impl_Account::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getBalance")) {

    _0RL_cd_4cbcfecae188e63d_00000000 _call_desc(_0RL_lcfn_4cbcfecae188e63d_10000000, "getBalance", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "withdraw")) {

    _0RL_cd_4cbcfecae188e63d_20000000 _call_desc(_0RL_lcfn_4cbcfecae188e63d_30000000, "withdraw", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "deposit")) {

    _0RL_cd_4cbcfecae188e63d_20000000 _call_desc(_0RL_lcfn_4cbcfecae188e63d_40000000, "deposit", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
SavingsAccount::_impl_Account::_ptrToInterface(const char* id)
{
  if (id == ::SavingsAccount::Account::_PD_repoId)
    return (::SavingsAccount::_impl_Account*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::SavingsAccount::Account::_PD_repoId))
    return (::SavingsAccount::_impl_Account*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
SavingsAccount::_impl_Account::_mostDerivedRepoId()
{
  return ::SavingsAccount::Account::_PD_repoId;
}

POA_SavingsAccount::Account::~Account() {}


// class Account_i : public
// {
// };
